apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      containers:
      - name: apiserver
        image: gpedroenrique/quizlet:apiserver
        imagePullPolicy: Always
        env:
          - name: QUIZ_API_KEY
            valueFrom:
              secretKeyRef:
                name: api-secrets
                key: API_KEY
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: mongo-credentials
                key: mongo-user
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-credentials
                key: mongo-password
          - name: MONGO_IP
            value: mongodb-service
          - name: MONGO_PORT
            value: "27017"
          - name: NODE_PORT
            value: "9001"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 9001

---

apiVersion: v1
kind: Service
metadata:
  name: apiserver-service
spec:
  type: NodePort
  selector:
    app: apiserver
  ports:
  - protocol: TCP
    port: 9001
    targetPort: 9001
    nodePort: 30001

