apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      containers:
      - name: apiserver
        image: europe-west1-docker.pkg.dev/whp-quiz-game/whp-quiz-repository/quiz-server:latest
        imagePullPolicy: Always
        env:
          - name: QUIZ_API_KEY
            valueFrom:
              secretKeyRef:
                name: api-secrets
                key: API_KEY
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: mongo-credentials
                key: mongo-user
          - name: SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: api-secrets
                key: SECRET_TOKEN
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-credentials
                key: mongo-password
          - name: MONGO_IP
            value: mongodb-service
          - name: MONGO_PORT
            valueFrom:
              secretKeyRef:
                name: mongo-credentials
                key: mongo-port
          - name: NODE_PORT
            value: "9001"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 9001

---

apiVersion: v1
kind: Service
metadata:
  name: api-server-service
spec:
  type: ClusterIP
  selector:
    app: apiserver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9001
    

