steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/whp-quiz-game/whp-quiz-repository/whp-quiz-game', '.' ]
images:
- 'europe-west1-docker.pkg.dev/whp-quiz-game/whp-quiz-repository/whp-quiz-game'