version: '3'
services:

  react-app:
    container_name: react-app
    build: 
      context: ./
      dockerfile: ./client.Dockerfile
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - 9011:9011
    depends_on:
      - api-server

  api-server:
    container_name: api-server
    build: 
      context: ./
      dockerfile: ./api.Dockerfile
    volumes:
      - ./server/:/api-server
      - /api-server/node_modules
    env_file: ./server/.env
    ports:
      - 9001:9001
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=app
    volumes:
      - db-volume:/data/db

volumes:
  db-volume: