version: '3'
services:

  react-app:
    container_name: react-app
    build: 
      context: ./
      dockerfile: ./client.Dockerfile
    volumes:
      - ./client:/client
      - /client/node_modules
    healthcheck:
      test: curl -f http://localhost:9011 || exit 1
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s
    ports:
      - 9011:9011
    depends_on:
      api-server:
        condition: service_healthy

  api-server:
    container_name: api-server
    build: 
      context: ./
      dockerfile: ./api.Dockerfile
    volumes:
      - ./server/:/api-server
      - /api-server/node_modules
    ports:
      - 9001:9001
    healthcheck:
      test: curl -f http://localhost:9001 || exit 1
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    container_name: mongodb
    image: mongo
    env_file:
      - ./server/.env
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    
    volumes:
      - db-volume:/data/db

volumes:
  db-volume: