version: '3'
services:

  # nginx:
  #   container_name: nginx-server
  #   image: nginx:stable-alpine

  #   volumes:
  #     - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  #   depends_on:
  #     - node-app

  #   networks:
  #     - quiz-network

  # react-app:
  #   container_name: react-app
  #   build: ./client
  #   environment:
  #     - REACT_APP_API_URL=http://nginx-server:4000
  #   volumes:
  #     - ./client:/client
  #     - /client/node_modules
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - node-app
  #     - nginx
  #   networks:
  #     - quiz-network

  api-server:
    container_name: api-server
    build: 
      context: ./server/api
      dockerfile: ./api.Dockerfile
    environment:
      - NODE_PORT=5000
    ports:
      - 5000:5000 # TODO: The api will eventually be behind a proxy and it will not be accesible from the internet.
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=infra
      - MONGO_INITDB_DATABASE=app
    volumes:
      - db-volume:/data/db
    # networks:
    #   - quiz-network

  # redis:
  #   container_name: redis
  #   image: redis
  #   hostname: redis
  #   networks:
  #     - quiz-network

volumes:
  db-volume:

# networks:
#   quiz-network:
#     driver: bridge
