apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
type: Opaque
data:
  mongo-user: aW5mcmE=
  mongo-password: Z29yZG9zaW5mdXR1cm8=
  mongo-port: MjcwMTc=
  mongo-ip: bW9uZ29kYg== # TODO: Set the mongo service ip currently 'ºmongodb'
